name: Playwright CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run Playwright Tests
        run: npx playwright install && npx playwright test
        continue-on-error: true

      - name: Generate Ortoni Report
        run: npx @ortoni/report

      - name: Upload Allure Results as artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results

      - name: Upload Ortoni Results as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ortoni-report
          path: ortoni-report
